version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: 
      context: ./client # specify the directory of the Dockerfile
      dockerfile: dev.dockerfile
    volumes: 
      - ./client:/usr/src/app
    ports:
      - "4200:4200" # specify port forewarding
    #volumes: 
    #   - .:/code

  express: #name of the second service
    build:
      context: ./server # specify the directory of the Dockerfile
      dockerfile: dev.dockerfile
    volumes: 
      - ./server:/usr/src/service
    ports:
      - "3000:3000" #specify ports forewarding
    networks:
      - mars-network
    # links:
    #     - database # link this service to the database service

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27018:27017" # specify port forewarding
    networks:
      - mars-network

networks:
  mars-network:
    driver: bridge
  
